// root layout (manage SEO here)

import { Inter } from 'next/font/google';
import './globals.css';
import Button from './components/Button';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Button text="🏠" />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
